---

- hosts: crm-server
  gather_facts: False
  user: root
  #  sudo: True
  #  gather_facts: True
  vars_files:
    - vars/common.yml
    - vars/database.yml
    - vars/mail.yml
    - vars/lists.yml
    - vars/tine.yml
    - vars/cert.yml
    - vars/passwords.yml
    - vars/inwx.yml
    - vars/inwxpasswd.yml
  roles:
    - up
    - common
    - database
    - webserver
    - mailserver
    - mailinglist
      # - domain
    - crm

