---

- name: clone amavisd-milter
  git:
    repo: "https://github.com/ThomasLeister/amavisd-milter.git"
    dest: "/root/amavisd-milter"

- name: build amavisd-milter
  shell: "./configure && make -j8 && make install"
  args:
    executable: "/bin/bash"
    chdir: "/root/amavisd-milter"

- name: install amavis
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - amavisd-new
    - libmilter-dev


