---

- name: Create Thunderbird autoconfig directory
  file:
    path: /var/www/autoconfig/mail/
    state: directory

- name: Copy Thunderbird autoconfig file
  template:
    src: ../templates/var/www/autoconfig/mail/config-v1.1.xml
    dest: '/var/www/autoconfig/mail/config-v1.1.xml'

- name: Process autoconfig template 
  template:
    src: "../templates/etc/apache2/sites-available/autoconfig.conf" 
    dest: "/etc/apache2/sites-available/autoconfig.conf"

- name: Enable thunderbird autoconfig
  shell: "a2ensite autoconfig.conf"
  args:
    executable: "/bin/bash"
  notify:
    - Restart postfix



