---

- name: Do not generate dovecot ssl-cert during install
  debconf:
    name: dovecot-core
    question: dovecot-core/create-ssl-cert
    value: false
    vtype: boolean

  #- name: Add newest dovecot repo to support imap_sieve
  #  apt_repository:
  #    repo: "ppa:pdoes/dovecot"

- name: Install dovecot and components
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - dovecot-core
    - dovecot-imapd
    - dovecot-mysql
    - dovecot-lmtpd
    - dovecot-pop3d
    - dovecot-sieve
    - dovecot-managesieved

- name: Copy dovecot SQL file
  copy:
    dest: /tmp/dovecot.sql
    src: ../files/dovecot.sql

- name: Create dovecot database
  mysql_db:
    name: dovecot
    state: present
    login_password: '{{ mysql_root_passwd }}'

- name: Init dovecot db
  mysql_db:
    name: dovecot
    state: import
    target: /tmp/dovecot.sql
    login_user: root
    login_password: '{{ mysql_root_passwd }}'
  ignore_errors: True

- meta: flush_handlers


- name: Set /var/mail deliver user (contains all mailboxes)
  file:
    path: "{{ item }}"
    owner: "{{ deliver_user_name }}"
    group: "{{ deliver_user_name }}"
    mode: 0770
    state: directory
  with_items:
    - "/var/mail"

- name: Process dovecot templates using /etc/dovecot exclusively
  include_tasks: ../../common/tasks/exclusivetemplate.yml
  vars:
    root: /etc/dovecot

- name: Set permissions of conf files containing password
  file:
    path: "{{ item }}"
    mode: 0640
    owner: root
    group: dovecot
  with_items:
    - /etc/dovecot/dovecot-sql.conf
    - /etc/dovecot/dovecot-dict-sql.conf

- name: Restart dovecot
  service:
    name: dovecot
    state: restarted
  ignore_errors: True


