---

- name: Do not generate dovecot ssl-cert during install
  debconf:
    name: dovecot-core
    question: dovecot-core/create-ssl-cert
    value: false
    vtype: boolean

- name: Install dovecot and components
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - dovecot-core
    - dovecot-imapd
    - dovecot-mysql
    - dovecot-lmtpd
    - dovecot-pop3d
    - dovecot-sieve
    - dovecot-managesieved
    - dovecot-antispam


- name: Copy dovecot SQL file
  copy:
    dest: /tmp/dovecot.sql
    src: ../files/dovecot.sql

- name: Create dovecot database
  mysql_db:
    name: dovecot
    state: present
    login_password: '{{ mysql_root_passwd }}'
  notify:
    - Init dovecot db

  #- name: Remove example ssl config 
  #  file:
  #    path: "/etc/dovecot/conf.d/10-ssl.conf"
  #    state: absent



- name: Clear /etc/dovecot/conf.d/
  file:
    name: "/etc/dovecot/conf.d"
    state: absent

- name: Recreate directory /etc/dovecot/conf.d/
  file:
    name: "/etc/dovecot/conf.d"
    mode: 0755
    owner: root
    group: root
    state: directory

- name: Process dovecot templates
  template:
    src: "{{ item.src }}"
    dest: "/etc/dovecot/{{ item.path }}"
  with_filetree: "../templates/etc/dovecot/"
  when: item.state == 'file'
  notify:
    - Restart dovecot




