---

- name: Do not generate dovecot ssl-cert during install
  debconf:
    name: dovecot-core
    question: dovecot-core/create-ssl-cert
    value: false
    vtype: boolean

- name: Install dovecot and components
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - dovecot-core
    - dovecot-imapd
    - dovecot-mysql
    - dovecot-lmtpd
    - dovecot-pop3d
    - dovecot-sieve
    - dovecot-managesieved
    - dovecot-antispam


- name: Copy dovecot SQL file
  copy:
    dest: /tmp/dovecot.sql
    src: ../files/dovecot.sql

- name: Create dovecot database
  mysql_db:
    name: dovecot
    state: present
    login_password: '{{ mysql_root_passwd }}'
  notify:
    - Init dovecot db

- name: Clear /etc/dovecot/
  file:
    name: "/etc/dovecot/"
    state: absent

- name: Recreate directory /etc/dovecot/conf.d/
  file:
    name: "{{ item }}"
    mode: 0755
    owner: root
    group: root
    state: directory
  with_items:
    - /etc/dovecot
    - /etc/dovecot/conf.d

- name: Process dovecot templates
  template:
    src: "{{ item.src }}"
    dest: "/etc/dovecot/{{ item.path }}"
  with_filetree: "../templates/etc/dovecot/"
  when: item.state == 'file'
  notify:
    - Restart dovecot

- name: Set permissions of conf files containing password
  file:
    path: "{{ item }}"
    mode: 0640
    owner: root
    group: dovecot
  with_items:
    - /etc/dovecot/dovecot-sql.conf
    - /etc/dovecot/dovecot-dict-sql.conf


