---

- name: create deliver user
  user:
    name: "{{ deliver_user_name }}"
    comment: user for mailserver

- name: copy sieve and spampipe templates
  template:
    src: "{{ item }}"
    dest: "/{{ item }}"
  with_fileglob:
    - "../templates/*"

- include: postfix.yml

- include: dovecot.yml

- include: amavis.yml

- include: opendkim.yml

- include: razor.yml


