---

- name: configure postfix mailname
  debconf:
    name: postfix
    question: postfix/mailname
    value: "{{ mailname }}"
    vtype: string

- name: configure postfix main mailer type
  debconf:
    name: postfix
    question: postfix/main_mailer_type
    value: "Internet Site"
    vtype: string

- name: install postfix
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - postfix
    - postfix-mysql

- name: postmap without_ptr
  shell: "postmap /etc/postfix/without_ptr"
  args:
    executable: "/bin/bash"

- name: postmap transport
  shell: "postmap /etc/postfix/transport"
  args:
    executable: "/bin/bash"


- name: Permissions /etc/postfix/sql
  file:
    path: /etc/postfix/sql
    #owner: "{{ deliver_user_name }}"
    #group: "{{ deliver_user_name }}"
    mode: 660
    state: directory
    recurse: yes


