---

- name: Configure postfix mailname - dummy
  debconf:
    name: postfix
    question: postfix/mailname
    value: "dummy"
    vtype: string

- name: Configure postfix main mailer type - No configuration
  debconf:
    name: postfix
    question: postfix/main_mailer_type
    value: "No configuration"
    vtype: select

- name: Install postfix
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - postfix
    - postfix-mysql

- name: Copy postfix SQL file
  copy:
    dest: /tmp/postfix.sql
    src: ../files/postfix.sql

- name: Create postfix database
  mysql_db:
    name: postfix
    state: present
    login_password: '{{ mysql_root_passwd }}'

- name: Init postfix db
  mysql_db:
    name: postfix
    state: import
    target: /tmp/postfix.sql
    login_user: root
    login_password: '{{ mysql_root_passwd }}'
  ignore_errors: True

- name: Create directory /etc/postfix/sql
  file:
    path: /etc/postfix/sql
    owner: root 
    group: root
    mode: 0660
    state: directory
    recurse: yes

- name: Process postfix templates
  template:
    src: "{{ item.src }}"
    dest: "/etc/postfix/{{ item.path }}"
  with_filetree: "../templates/etc/postfix"
  when: item.state == 'file'
  #  notify:
  #    - Restart postfix

- name: Process /etc/aliases template
  template:
    src: "../templates/etc/aliases"
    dest: "/etc/aliases"

- name: Copy rc.local
  copy:
    dest: "/etc/rc.local"
    src: "../files/etc/rc.local"

- name: Run rc.local
  shell: "/bin/bash /etc/rc.local"
  args:
    executable: "/bin/bash"

- name: Update permissions for /etc/postfix/sql
  file:
    path: /etc/postfix/sql
    owner: root 
    group: root
    mode: 0660
    state: directory
    recurse: yes

- name: Postmap without_ptr
  shell: "postmap /etc/postfix/without_ptr"
  args:
    executable: "/bin/bash"

- name: Postmap virtual mailman domains
  shell: "postmap /etc/postfix/virtual_mailman_domains"
  args:
    executable: "/bin/bash"

- name: Newaliases needed
  shell: "newaliases"
  args:
    executable: "/bin/bash"

