---

- name: Enable apache2 proxy
  apache2_module:
    state: present
    name: "{{ item }}"
    ignore_configcheck: True
  with_items:
    - proxy
    - proxy_http
  ignore_errors: True

- name: Process rspamd gui template 
  template:
    src: "../templates/etc/apache2/sites-available/rspamd.conf" 
    dest: "/etc/apache2/sites-available/rspamd.conf"

- name: Enable rspamd gui
  shell: "a2ensite rspamd.conf"
  args:
    executable: "/bin/bash"

- name: Restart apache2
  systemd:
    name: apache2
    state: restarted
  ignore_errors: True

