---

- name: install apt-transport-https 
  apt: 
    name: apt-transport-https
    state: present
    update_cache: yes

- name: add tine20 repo
  apt_repository:
    repo: "deb https://packages.tine20.org/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"
    state: present
    update_cache: yes

