---

- name: Install apt-transport-https 
  apt: 
    name: apt-transport-https
    state: present
    update_cache: yes

- name: Add tine20 repo
  apt_repository:
    repo: "deb https://packages.tine20.org/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"
    state: present
    update_cache: yes

- name: apt-key
  apt_key:
    keyserver: keys.gnupg.net
    id: 8825FD82
    state: present

- name: Get tine20
  apt:
    name: tine20
    state: latest
    force: yes

- name: Enable https
  apache2_module:
    state: present
    name: ssl
    ignore_configcheck: True
  notify:
    - Restart apache2
  ignore_errors: true

- name: Run all handlers before installing tine20
  meta: flush_handlers

- name: Install tine20
  shell: 'php /usr/share/tine20/setup.php -c /etc/tine20 --install -- adminLoginName="{{ tine20_admin_name }}" adminPassword="{{ tine20_admin_passwd }}" acceptedTermsVersion=1000 adminEmailAddress="{{ tine20_admin_name }}@{{ domain }}" imap="host:{{ tine20_mailhost }},port:143,useSystemAccount:1,domain:{{ domain }},ssl:none,useEmailAsUsername:0,backend:dovecot_imap,dovecot_host:{{ dbhost }},dovecot_dbname:dovecot,dovecot_username:{{ mailserver_db_user_name }},dovecot_password:{{ mailserver_db_user_passwd }},dovecot_uid:{{ deliver_user_name }},dovecot_gid:{{ deliver_user_name }},dovecot_home:/var/spool/mail/%d/%n,dovecot_scheme:SSHA512" smtp="backend:postfix,hostname:{{ tine20_mailhost }},port:587,ssl:tls,auth:login,primarydomain:{{ domain }},secondarydomains:{{ secondarydomains }},username:tine20@{{ domain }},password:tine20,from:tine20@{{ domain }},postfix_host:{{ dbhost }},postfix_dbname:postfix,postfix_username:{{ mailserver_db_user_name }},postfix_password:{{ mailserver_db_user_passwd }}" sieve="hostname:{{ tine20_mailhost }},port:4190,ssl:tls"'
  args:
    executable: "/bin/bash"
  notify:
    - Restart apache2

- name: TLS required
  blockinfile:
    path: /etc/tine20/apache.conf
    marker: "# {mark} Ansible crm/tine https config"
    content: | 
      <VirtualHost *:80>
        ServerName   {{ domain }}
        Redirect permanent /tine20 https://{{ domain }}/tine20
      </VirtualHost>

      <VirtualHost *:443>
        SSLEngine on
        SSLCertificateFile {{ certbaselocation }}/{{ domain }}/fullchain.pem
        SSLCertificateKeyFile {{ certbaselocation }}/{{ domain }}/privkey.pem
        DocumentRoot /usr/share/tine20
        ServerName   {{ domain }}
      </VirtualHost>
      
  notify:
    - Restart apache2







