---

- name: Install apt-transport-https 
  apt: 
    name: apt-transport-https
    state: present
    update_cache: yes

- name: apt-key
  apt_key:
    keyserver: keys.gnupg.net
    id: 8825FD82
    state: present

- name: Add tine20 repo
  apt_repository:
    repo: "deb https://packages.tine20.org/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"
    state: present
    update_cache: yes

- name: Get tine20
  apt:
    name: "{{ item }}"
    state: latest
    force: yes
  with_items:
    - apt-utils
    - sudo
    - tine20
      #- tine20-voipmanager
      #- tine20-events
      #- tine20-courses
      #- tine20-phone
      #- tine20-projects
      #- tine20-worker

- name: Enable https
  apache2_module:
    state: present
    name: ssl
    ignore_configcheck: True
  notify:
    - Restart apache2
  ignore_errors: true

- name: Run all handlers before installing tine20
  meta: flush_handlers

- name: Create log dir with permissions
  file:
    name: "/var/log/tine20"
    state: directory
    mode: 0750
    owner: www-data
    group: root

- name: Install tine20
  shell: |
   php /usr/share/tine20/setup.php -c /etc/tine20 --install all -- adminLoginName={{ tine20_admin_name }} adminPassword={{ tine20_admin_passwd }} acceptedTermsVersion=1000 adminEmailAddress={{ tine20_admin_name }}@{{ emaildomain }} imap=host:{{ tine20_mailhost }},port:143,useSystemAccount:1,domain:{{ imapuserdomain }},ssl:none,useEmailAsUsername:0,backend:dovecot_imap,dovecot_host:{{ dbhost }},dovecot_dbname:dovecot,dovecot_username:{{ mailserver_db_user_name }},dovecot_password:{{ mailserver_db_user_passwd }},dovecot_uid:{{ deliver_user_name }},dovecot_gid:{{ deliver_user_name }},dovecot_home:/var/spool/mail/%d/%n,dovecot_scheme:SSHA512 smtp='{"active":true,"backend":"postfix","hostname":"{{ tine20_mailhost }}","port":25,"ssl":"none","auth":"none","primarydomain":"{{ imapuserdomain }}","secondarydomains":"{{ allemaildomains | join(',') }}","username":"tine20@{{ imapuserdomain }}","password":"tine20","from":"tine20@{{ domain }}","postfix":{"host":"{{ dbhost }}","dbname":"postfix","username":"{{ mailserver_db_user_name }}","password":"{{ mailserver_db_user_passwd }}"} }' sieve=hostname:{{ tine20_mailhost }},port:4190,ssl:none
  args:
    executable: "/bin/bash"
  become: True
  become_user: "www-data"
  notify:
    - Restart apache2

- name: Set sieve Configuration of tine20 again
  shell: |
    php /usr/share/tine20/setup.php -c /etc/tine20 --setconfig configkey='sieve' configvalue='hostname:{{ tine20_mailhost }},port:4190,ssl:none'
  args:
    executable: "/bin/bash"
  become: True
  become_user: "www-data"
  notify:
    - Restart apache2

- name: Set smtp Configuration of tine20 again
  shell: |
      php /usr/share/tine20/setup.php -c /etc/tine20 --setconfig configkey='smtp' configvalue='{"active":true,"backend":"postfix","hostname":"{{ tine20_mailhost }}","port":25,"ssl":"none","auth":"none","primarydomain":"{{ imapuserdomain }}","secondarydomains":"{{ allemaildomains | join(',') }}","username":"tine20@{{ domain }}","password":"tine20","from":"tine20@{{ domain }}","postfix":{"host":"{{ dbhost }}","dbname":"postfix","username":"{{ mailserver_db_user_name }}","password":"{{ mailserver_db_user_passwd }}"} }'
  args:
    executable: "/bin/bash"
  become: True
  become_user: "www-data"
  notify:
    - Restart apache2

- name: Set imap Configuration of tine20 again
  shell: |
      php /usr/share/tine20/setup.php -c /etc/tine20 --setconfig configkey='imap' configvalue='host:{{ tine20_mailhost }},port:143,useSystemAccount:1,domain:{{ imapuserdomain }},ssl:none,useEmailAsUsername:0,backend:dovecot_imap,dovecot_host:{{ dbhost }},dovecot_dbname:dovecot,dovecot_username:{{ mailserver_db_user_name }},dovecot_password:{{ mailserver_db_user_passwd }},dovecot_uid:{{ deliver_user_name }},dovecot_gid:{{ deliver_user_name }},dovecot_home:/var/spool/mail/%d/%n,dovecot_scheme:SSHA512'
  args:
    executable: "/bin/bash"
  become: True
  become_user: "www-data"
  notify:
    - Restart apache2

- name: Update tine20
  shell: 'php /usr/share/tine20/setup.php -c /etc/tine20 --update all'
  args:
    executable: "/bin/bash"
  become: True
  become_user: "www-data"
  notify:
    - Restart apache2

- name: Set log file permissions
  file:
    name: "/var/log/tine20/tine20.log"
    state: file
    mode: 0644
    owner: www-data
    group: www-data

- name: TLS required
  blockinfile:
    path: /etc/tine20/apache.conf
    marker: "# {mark} Ansible crm/tine https config"
    content: | 
      {% for item in tinedomains %}
      <VirtualHost *:80>
        ServerName   {{ item }}
        Redirect permanent / https://{{ item }}/
      </VirtualHost>

      <VirtualHost *:443>
        SSLEngine on
        SSLUseStapling on
        SSLOpenSSLConfCmd DHParameters /etc/myssl/dh4096.pem
        Header always set Strict-Transport-Security "max-age=63072000; includeSubdomains;"
        SSLCertificateFile {{ certbaselocation }}/{{ item }}/fullchain.pem
        SSLCertificateKeyFile {{ certbaselocation }}/{{ item }}/privkey.pem
        DocumentRoot /usr/share/tine20
        ServerName   {{ item }}
      </VirtualHost>
      {% endfor %}
  notify:
    - Restart apache2







