---

- name: Configure mysql-server root password
  debconf:
    name: mysql-server
    question: mysql-server/root_password
    value: "{{ mysql_root_passwd }}"
    vtype: password

- name: Repeate mysql-server root password
  debconf:
    name: mysql-server
    question: mysql-server/root_password_again
    value: "{{ mysql_root_passwd }}"
    vtype: password

- name: Install mysql and libs
  package:
    name:
      - mysql-server
      - mysql-client
      - mysql-utilities
      - libdbi-perl
      - libdbd-mysql-perl
      - python-mysqldb
    state: latest


