---

# This does NOT set /etc/hostname as hostname --fqdn, it uses first entry in /etc/hosts !
# This is important for amavis, it reads histname --fqdn
- name: Hostname 
  shell: "hostname -F /etc/hostname"
  args:
    executable: '/bin/bash'

- name: Restart unbound
  service:
    name: unbound
    state: restarted

- name: Unbound anchor
  shell: "/usr/sbin/unbound-anchor ; echo $?"
  args:
    executable: "/bin/bash"

- name: Generate openssl dh parameters
  shell: "FILE=`mktemp` ; openssl dhparam 2048 -out $FILE && mv -f $FILE /etc/myssl/dh2048.pem &"
  args:
    executable: '/bin/bash'



