---

- name: Configure mailman create_site_list
  debconf:
    name: mailman
    question: mailman/create_site_list
    value: true 
    vtype: note

- name: Configure mailman site_language
  debconf:
    name: mailman
    question: mailman/site_languages
    value: de
    vtype: multiselect

- name: Install mailman
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - mailman
  notify:
    - Newlist mailman
    - mailman db files

- name: Create directories 
  file:
    path: "{{ item }}"
    owner: root
    group: root
    mode: 0755
    state: directory
  with_items:
    - "/etc/mailman"

- name: Process mailman templates
  template:
    src: "{{ item.src }}"
    dest: "/etc/mailman/{{ item.path }}"
  with_filetree: "../templates/etc/mailman/"
  when: item.state == 'file'
  notify:
    - Restart mailman

- name: Add mailman to apache2
  shell: "cp /etc/mailman/apache.conf /etc/apache2/sites-available/mailman.conf"
  args:
    executable: "/bin/bash"

- name: Activate cgid in apache2
  apache2_module:
    state: present
    name: cgid
    ignore_configcheck: true
  ignore_errors: true

- name: Activate mailman in apache2
  shell: "a2ensite mailman.conf"
  args:
    executable: "/bin/bash"
  notify:
    - Restart apache2


- name: Add user postfix to group list
  user:
    name: postfix
    groups: list
    append: yes  

- name: Set list creators password
  shell: "mmsitepass {{ list_creators_passwd }}"
  args:
    executable: "/bin/bash"




