---

- name: Secondary domains with mailman prefix as csv
  set_fact:
    secondary_mailman_domains_csv: "{% if secondarydomains %}{% for d in secondarydomains %}{{ mailman_prefix }}.{{ d }}{% if not loop.last %}, {% endif %}{% endfor %}{% endif %}" 

- name: All domains with mailman prefix as csv
  set_fact:
    mailman_domains_csv: "{{ mailman_prefix }}.{{ domain }}{% if secondary_mailman_domains_csv %}, {% endif %}{{ secondary_mailman_domains_csv }}" 
 
- name: Secondary domains with mailman prefix as python list
  set_fact:
    secondary_mailman_domains_pylist: "{% if secondarydomains %}{% for d in secondarydomains %}'{{ mailman_prefix }}.{{ d }}'{% if not loop.last %}, {% endif %}{% endfor %}{% endif %}" 

- name: All domains with mailman prefix as python list
  set_fact:
    mailman_domains_pylist: "'{{ mailman_prefix }}.{{ domain }}'{% if secondary_mailman_domains_pylist %}, {% endif %}{{ secondary_mailman_domains_pylist }}" 

- name: Configure mailman create_site_list
  debconf:
    name: mailman
    question: mailman/create_site_list
    value: true 
    vtype: note

- name: Configure mailman site_language
  debconf:
    name: mailman
    question: mailman/site_languages
    value: de
    vtype: multiselect

- name: Install mailman
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - mailman
  #notify:
  #  - Newlist mailman

- name: Create directories 
  file:
    path: "{{ item }}"
    owner: root
    group: root
    mode: 0755
    state: directory
  with_items:
    - "/etc/mailman"

- name: Process mailman templates
  template:
    src: "{{ item.src }}"
    dest: "/etc/mailman/{{ item.path }}"
  with_filetree: "../templates/etc/mailman/"
  when: item.state == 'file'
  notify:
    - Restart mailman

  #- name: Connect mailman to postfix - main.cf
  #  blockinfile:
  #    dest: "/etc/postfix/main.cf"
  #    marker: "# {mark} ANSIBLE MANAGED BLOCK for mailman"
  #    content: |
  #      relay_recipient_maps = hash:/var/lib/mailman/data/virtual-mailman
  #      mailman_destination_recipient_limit = 1
  #
  #- name: Connect mailman to postfix - transport
  #  blockinfile:
  #    dest: "/etc/postfix/transport"
  #    create: True
  #    marker: "# {mark} ANSIBLE MANAGED BLOCK for mailman - {{ mailman_prefix }}.{{ item }}"
  #    content: |
  #      {{ mailman_prefix }}.{{ item }} mailman:
  #  with_items:
  #    - "{{ domain }}"
  #    - "{{ secondarydomains }}"
  #
  #- name: Connect mailman to postfix - relaydomains
  #  blockinfile:
  #    dest: "/etc/postfix/relaydomains"
  #    create: True
  #    marker: "# {mark} ANSIBLE MANAGED BLOCK for mailman - {{ mailman_prefix }}.{{ item }}"
  #    content: |
  #      {{ mailman_prefix }}.{{ item }}
  #  with_items:
  #    - "{{ domain }}"
  #    - "{{ secondarydomains }}"
  #
  #- name: Postmap transport
  #  shell: "postmap /etc/postfix/transport"
  #
  #- name: Postmap relaydomains
  #  shell: "postmap /etc/postfix/relaydomains"
  #
  #
  #- name: Connect mailman to postfix - master.cf
  #  blockinfile:
  #    dest: "/etc/postfix/master.cf"
  #    marker: "# {mark} ANSIBLE MANAGED BLOCK for mailman"
  #    content: |
  #      mailman   unix  -       n       n       -       -       pipe
  #        flags=FR user=list argv=/usr/lib/mailman/bin/postfix-to-mailman.py ${nexthop} ${recipient}

- name: Configure mailman
  blockinfile:
    dest: "/etc/mailman/mm_cfg.py"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - {{ mailman_prefix }}.{{ item }}"
    content: |
      add_virtualhost( '{{ mailman_prefix }}.{{ item }}', '{{ mailman_prefix }}.{{ item }}' )
  with_items:
    - "{{ domain }}"
    - "{{ secondarydomains }}"

- name: Add mailman to apache2
  template:
    dest: "/etc/apache2/sites-available/mailman.conf"
    src: "../templates/etc/apache2/sites-available/mailman.conf"

- name: Add mailman domains to apache2
  blockinfile:
    dest: "/etc/apache2/sites-available/mailman.conf"
    insertbefore: "^# Ansible block position"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - {{ mailman_prefix }}.{{ item }}"
    content: |
      <VirtualHost *:80>
          ServerName {{ mailman_prefix }}.{{ item }}
          Redirect / https://{{ mailman_prefix }}.{{ item }}/
      </VirtualHost>
  with_items:
    - "{{ domain }}"
    - "{{ secondarydomains }}"

- name: Activate cgid in apache2
  apache2_module:
    state: present
    name: cgid
    ignore_configcheck: true
  ignore_errors: true

- name: Activate mailman in apache2
  shell: "a2ensite mailman.conf"
  args:
    executable: "/bin/bash"
  notify:
    - Restart apache2

- name: Add user postfix to group list
  user:
    name: postfix
    groups: list
    append: yes  

- name: Set list creators password
  shell: "mmsitepass {{ list_creators_passwd }}"
  args:
    executable: "/bin/bash"

- name: Newlist mailman
  shell: 'echo -e "\n" | /usr/sbin/newlist mailman {{ mailman_email }} {{ mailman_passwd }}'
  args:
    executable: /bin/bash
  ignore_errors: True

  #- name: Initial list must be created to generate virtual-mailman
  #  meta: flush_handlers

  #- name: Mailman genaliases
  #  shell: '/var/lib/mailman/bin/genaliases'
  #  args:
  #    executable: /bin/bash

- name: Permissions for /var/lib/mailman/data/aliases.db
  file:
    name: /var/lib/mailman/data/aliases.db
    state: file
    owner: www-data
    group: list

- name: Permissions for /var/lib/mailman/data/virtual-mailman.db
  file:
    name: /var/lib/mailman/data/virtual-mailman.db
    state: file
    owner: www-data
    group: list


