---


- name: Install unbound
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - unbound
    - dnsutils

- name: Copy unbound config
  copy:
    src: "../files/etc/unbound/"
    dest: "/etc/unbound/"

- name: Copy dhcp config
  copy:
    src: "../files/etc/dhcp/"
    dest: "/etc/dhcp/"

- name: set /etc/unbound owner
  file:
    name: /etc/unbound
    owner: unbound

- name: Unbound anchor
  shell: "/usr/sbin/unbound-anchor ; echo $?"
  args:
    executable: "/bin/bash"

- name: Restart unbound
  service:
    name: unbound
    state: restarted


