---


- name: Install unbound
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - unbound
    - dnsutils

- name: Create unbound directories (incl. dhcp) 
  file:
    path: "{{ item }}"
    owner: root
    group: root
    mode: 0755
    state: directory
  with_items:
    - "/etc/dhcp"
    - "/etc/unbound"
    - "/etc/unbound/unbound.conf.d"

- name: Copy unbound config
  copy:
    src: "../files/etc/unbound/"
    dest: "/etc/unbound/"

- name: Copy dhcp config
  copy:
    src: "../files/etc/dhcp/"
    dest: "/etc/dhcp/"

- name: Process /etc/hosts template
  template:
    src: "../templates/etc/hosts"
    dest: "/etc/hosts"

- name: set /etc/unbound owner
  file:
    name: /etc/unbound
    owner: unbound
  notify:
    - Unbound anchor
    - Restart unbound



