---

- name: Secondary domains as csv
  set_fact:
    secondary_domains_csv: "{% if secondarydomains %}{% for d in secondarydomains %}{{ d }}{% if not loop.last %},{% endif %}{% endfor %}{% endif %}" 

- name: All domains as csv
  set_fact:
    domains_csv: "{{ domain }}{% if secondary_domains_csv %},{% endif %}{{ secondary_domains_csv }}" 
 
- name: All domains as ssv
  set_fact:
    domains_ssv: "{{ domain }}{% if secondary_domains_csv %} {% endif %}{{ secondary_domains_csv }}" 
 
- name: Get IPv4
  uri:
    url: "http://ipv4.icanhazip.com"
    return_content: yes
  register: get_ipv4_res
  
- name: Set IPv4 var
  set_fact: 
    myextip: "{{ get_ipv4_res.content }}"

- name: Get IPv6
  uri:
    url: "http://ipv6.icanhazip.com"
    return_content: yes
  register: get_ipv6_res
  
- name: Set IPv6 var
  set_fact: 
    myextip6: "{{ get_ipv6_res.content }}"

- name: Set hostname persistant
  copy:
    content: "{{ hostname }}"
    dest: "/etc/hostname"
  become: yes
  become_method: sudo
  notify: 
    - Hostname
    - Reboot

- meta: flush_handlers

  #- include: reboot.yml

- name: Force ipv4 for apt
  copy:
    content: "Acquire::ForceIPv4 \"true\";"
    dest: "/etc/apt/apt.conf.d/99force-ipv4"
  #  become: yes
  #  become_method: sudo

- name: Install common packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - unzip
    - make
    - git
    - g++
    - make
    - cmake

- name: Install cronjobs
  blockinfile:
    path: /etc/crontab
    marker: "# {mark} -- Ansible mailserver/tine config"
    state: present
    create: yes
    block: |
      # DH parameter re-generation
      @daily		root	FILE=`mktemp` ; openssl dhparam 2048 -out $FILE && mv -f $FILE /etc/myssl/dh2048.pem
      # certificate renewal every month
      @monthly	root	/opt/certbot-auto renew --quiet --no-self-upgrade
      # Spamassassin care
      @daily		root	/root/sa-care.sh

- include: dns.yml

- include: ssl.yml

  #- include: domain_mgr.yml

  #- include: certbot.yml

