---

- include: calcnames.yml

- name: Get IPv4
  uri:
    url: "http://ipv4.icanhazip.com"
    return_content: yes
  register: get_ipv4_res
  
- name: Set IPv4 var
  set_fact: 
    myextip: "{{ get_ipv4_res.content }}"

- name: Get IPv6
  uri:
    url: "http://ipv6.icanhazip.com"
    return_content: yes
    timeout: 5
  register: get_ipv6_res
  ignore_errors: True
  
- name: Set IPv6 var
  set_fact: 
    myextip6: "{{ get_ipv6_res.content }}"

- name: Process /etc/hosts template - sets FQDN
  template:
    src: "../templates/etc/hosts"
    dest: "/etc/hosts"

- name: Set hostname persistant
  hostname:
    name: "{{ hostname }}"

- name: Set hostname immediately, reloads also FQDN from /etc/hosts
  shell: "hostname -F /etc/hostname"

- name: Force ipv4 for apt
  copy:
    content: "Acquire::ForceIPv4 \"true\";"
    dest: "/etc/apt/apt.conf.d/99force-ipv4"

- name: Install common packages
  apt:
    name:
      - unzip
      - make
      - git
      - g++
      - make
      - cmake
    state: latest
    update_cache: yes

- include: dns.yml

- include: ssl.yml


