---

- name: Concat all secondary domains
  set_fact:
    secondarydomains: "{{ emailmaps | map(attribute='mx') | unique | list }}"

- name: Concat all secondary email domains
  set_fact:
    secondaryemaildomains: "{{ emailmaps | map(attribute='emaildomain') | unique | list }}"

- name: Concat all secondary list web domains
  set_fact:
    secondarylistwebdomains: "{{ listmaps | map(attribute='webdomain') | unique | list }}"

- name: Concat all secondary list email domains
  set_fact:
    secondarylistemaildomains: "{{ listmaps | map(attribute='emaildomain') | unique | list }}"

- name: Concat domains unique
  set_fact:
    alldomains: "{{ ( [ domain ] + [ mailman_domain ] + secondarydomains + secondarylistwebdomains ) | unique | list }}"

- name: Concat email domains unique
  set_fact:
    allemaildomains: "{{ ( [ emaildomain ] + secondaryemaildomains + secondarylistemaildomains ) | unique | list }}"

- name: Concat all email, web, domain maps unique
  set_fact:
    allmaps: "{{ ( [ {'emaildomain': emaildomain , 'webdomain': domain , 'mx':  domain  } ] + emailmaps + listmaps ) | unique | list }}"

- name: Get all top level domains
  set_fact:
    alltlds: "{{ ( [ tld ] + secondarytlds ) | unique | list }}"

- name: Secondary domains as csv
  set_fact:
    secondary_domains_csv: "{{ secondarydomains | join(',') }}" 

- name: Secondary email domains as csv
  set_fact:
    secondary_email_domains_csv: "{{ secondaryemaildomains | join(',') }}" 

- name: Secondary domains as ssv
  set_fact:
    secondary_domains_ssv: "{{ secondarydomains | join(' ') }}" 

- name: Secondary email domains as ssv
  set_fact:
    secondary_email_domains_ssv: "{{ secondaryemaildomains | join(' ') }}" 

- name: All domains as csv
  set_fact:
    domains_csv: "{{ alldomains | join(',') }}" 
 
- name: All email domains as csv
  set_fact:
    email_domains_csv: "{{ allemaildomains | join(',') }}" 
 
- name: All domains as ssv
  set_fact:
    domains_ssv: "{{ alldomains | join(' ') }}" 
 
- name: All email domains as ssv
  set_fact:
    email_domains_ssv: "{{ allemaildomains | join(' ') }}" 

# mailman part - should be here, because also needed before mailman install/config (e.g. for domain) 
- name: Secondary domains with mailman prefix as csv
  set_fact:
    secondary_mailman_domains_csv: "{% if secondarydomains %}{{ mailman_prefix+'.'+secondarydomains | join(', '+mailman_prefix+'.')}}{% endif %}" 

- name: Secondary domains with mailman prefix as ssv
  set_fact:
    secondary_mailman_domains_ssv: "{% if secondarydomains %}{{ mailman_prefix+'.'+secondarydomains | join(' '+mailman_prefix+'.')}}{% endif %}" 

- name: All domains with mailman prefix as csv
  set_fact:
   #mailman_domains_csv: "{{ mailman_prefix+'.'+alldomains | join(', '+mailman_prefix+'.')}}" 
    mailman_domains_csv: "{{ secondarylistwebdomains | join(', ') }}" 

- name: All domains with mailman prefix as ssv
  set_fact:
   #mailman_domains_ssv: "{{ mailman_prefix+'.'+alldomains | join(' '+mailman_prefix+'.')}}" 
    mailman_domains_ssv: "{{ secondarylistwebdomains | join(' ') }}" 
 
- name: Secondary domains with mailman prefix as python list
  set_fact:
   #secondary_mailman_domains_pylist: "{% if secondarydomains %}{% for d in secondarydomains %}'{{ mailman_prefix }}.{{ d }}'{% if not loop.last %}, {% endif %}{% endfor %}{% endif %}" 
   secondary_mailman_domains_pylist: "{% if secondarylistemaildomains %}{% for d in secondarylistemaildomains %}'{{ d }}'{% if not loop.last %}, {% endif %}{% endfor %}{% endif %}" 
  #
- name: All domains with mailman prefix as python list
  set_fact:
   #mailman_domains_pylist: "{% if alldomains %}{% for d in alldomains %}'{{ mailman_prefix }}.{{ d }}'{% if not loop.last %}, {% endif %}{% endfor %}{% endif %}" 
    mailman_domains_pylist: "'{{ mailman_prefix }}.{{ domain }}', {{ secondary_mailman_domains_pylist }}" 
# end mailman part

- name: Get IPv4
  uri:
    url: "http://ipv4.icanhazip.com"
    return_content: yes
  register: get_ipv4_res
  
- name: Set IPv4 var
  set_fact: 
    myextip: "{{ get_ipv4_res.content }}"

- name: Get IPv6
  uri:
    url: "http://ipv6.icanhazip.com"
    return_content: yes
  register: get_ipv6_res
  ignore_errors: True
  
- name: Set IPv6 var
  set_fact: 
    myextip6: "{{ get_ipv6_res.content }}"

- name: Set hostname persistant
  hostname:
    name: "{{ hostname }}"
  #  copy:
  #    content: "{{ hostname }}"
  #    dest: "/etc/hostname"
  #  become: yes
  #  become_method: sudo
  notify: 
    - Hostname
    - Reboot

- meta: flush_handlers

- name: Force ipv4 for apt
  copy:
    content: "Acquire::ForceIPv4 \"true\";"
    dest: "/etc/apt/apt.conf.d/99force-ipv4"

- name: Install common packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - unzip
    - make
    - git
    - g++
    - make
    - cmake

- include: dns.yml

- include: ssl.yml


