---

- name: Set ssl-cert hostname (domain)
  debconf:
    name: ssl-cert
    question: make-ssl-cert/hostname
    value: "{{ domain }}"
    vtype: string

- name: Create /etc/myssl
  file:
    name: "/etc/myssl"
    state: directory
    owner: root
    group: root

- name: Copy cron file
  copy:
    dest: "/etc/cron.d/dhparam"
    src: "../files/etc/cron.d/dhparam"
    mode: 0644
    owner: root
    group: root

  #- name: Immediatelly create dhparams
  #  shell: "openssl dhparam -out /etc/myssl/dh2048.pem 512"
  #
  #- name: Immediatelly create dhparams
  #  shell: "openssl dhparam -out /etc/myssl/dh4096.pem 512"

