---

- name: Set ssl-cert hostname (domain)
  debconf:
    name: ssl-cert
    question: make-ssl-cert/hostname
    value: "{{ domain }}"
    vtype: string

- name: Create /etc/myssl
  file:
    name: "/etc/myssl"
    state: directory
    owner: root
    group: root
  notify:
    - Generate openssl dh parameters

