---

- name: Install apache2 webserver
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - apache2
    - php5
    - php5-mysql

- name: Enable https
  apache2_module:
    state: present
    name: ssl
    ignore_configcheck: True
  notify:
    - Restart apache2

