---

- name: Install apache2 webserver
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - apache2
    - php5
    - php5-mysql

- name: Create Maildir for www-data
  file:
    path: /var/www/Maildir
    owner: www-data
    group: www-data
    state: directory


