---

- name: Install apache2 webserver
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - apache2
    - php
    - libapache2-mod-php
    - php-mysql

- name: Enable some modules
  apache2_module:
    state: present
    name: "{{ item }}"
    ignore_configcheck: true
  ignore_errors: true 
  with_items:
    - ssl
    - headers
    - rewrite

- name: Make SSL more secure
  lineinfile:
    path: /etc/apache2/mods-enabled/ssl.conf
    regexp: '^[\s\#]*{{ item.key }}'
    line: "{{ item.key }} {{ item.value }}"
    insertbefore: "</IfModule>"
  with_dict: { SSLOpenSSLConfCmd ECDHParameters: "Automatic", SSLOpenSSLConfCmd Curves: "secp521r1:secp384r1:prime256v1", SSLHonorCipherOrder: "on", SSLOpenSSLConfCmd DHParameters: "/etc/myssl/dh4096.pem", SSLStaplingCache: "shmcb:/var/lib/apache2/ssl_stapling(32768)", SSLProtocol: "all -SSLv2 -SSLv3 -TLSv1 -TLSv1.1", SSLCipherSuite: "AES256+EECDH:AES256+EDH:!aNULL" }


