---

- name: Install apache2 webserver
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - apache2
    - php
    - libapache2-mod-php
    - php-mysql

- name: Enable https
  apache2_module:
    state: present
    name: ssl
    ignore_configcheck: true
  notify:
    - Restart apache2
  ignore_errors: true 

  #- name: Set www-data Maildir 
  #  file:
  #    path: "{{ item }}"
  #    owner: "www-data"
  #    group: "www-data"
  #    mode: 0770
  #    state: directory
  #  with_items:
  #    - "/var/www/Maildir"

